### ISSUE TITLE
f64 support

### ISSUE THREAD

**Issue by ExpHP** [raskr/rust-autograd#13]
I'm surveying this crate for possible use in physics code, and can't help but notice that all tensors are confined to single-precision floating point numbers. Basically, physics is chock-full of multivariate functions with [insanely complicated derivatives](https://github.com/lammps/lammps/blob/2558509b70fdd579b8c80174f0f83d9725ee43c8/src/MANYBODY/pair_airebo.cpp#L1257-L2085) that provide an immense barrier to their implementation; so automatic differentiation could be potentially very useful.  However, sometimes these functions may involve sums of signed values that wildly differ in magnitude, making `f32` a dangerous choice for implementation.

Making the crate generic over this would of course not be a trivial effort, as it will appear in virtually all traits and types.  You would also most likely need to depend on the `Float` trait from `num` or similar.

Note this probably isn't the only blocker towards the crate's use in these applications, and I can understand if you don't want to add this support for only the remote chance of attracting people from other disciplines.

**Comment by raskr** [comment]
Yes, this project currently supports f32 only, and I'm aware that restriction is too strong.

autograd depends on `ndarray` crate that can play with `num_traits::Float`, therefore it is possible to make `Tensor` type generic probably.
So... going to implement that when I get time (before long).

**Comment by raskr** [comment]
Implemented.  v0.9.1 supports `Float`.
