### ISSUE TITLE
Compile failure on example (intel-mkl-src)

### ISSUE THREAD

**Issue by OmnipotentEntity** [raskr/rust-autograd#21]
When attempting to compile an example application, using the suggested cargo invocation on crates.io (`autograd = { version = "0.9.5", features = ["mkl"] }`), I get the following error:

```
error: failed to run custom build command for `intel-mkl-src v0.2.5`

Caused by:
  process didn't exit successfully: `/path/to/project/target/debug/build/intel-mkl-src-2710610bac526c6f/build-script-build` (exit code: 101)
--- stdout
Downlaod archive

--- stderr
thread 'main' panicked at 'check sum of downloaded archive is incorrect: md5sum=d41d8cd98f00b204e9800998ecf8427e', /path/to/.cargo/registry/src/github.com-1ecc6299db9ec823/intel-mkl-src-0.2.5/build.rs:88:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Workaround is possible by simply not using `mkl`.

**Comment by OmnipotentEntity** [comment]
Further, actually running the [LSTM example](https://github.com/raskr/rust-autograd/blob/master/examples/lstm_lm.rs#L104) results in a panic:

`thread 'main' panicked at 'Shape error: placeholder required [-1, 2], but got [2, 3]',`

**Comment by raskr** [comment]
Fixed the bug in LSTM example, but I couldn't reproduce the checksum bug...
