### ISSUE TITLE
`argmax` with multiple maximum values

### ISSUE THREAD

**Issue by shanegibbs** [raskr/rust-autograd#4]
The library is working really great so far :tada: I am just seeing some interesting behaviour with `ag::argmax()`. I am passing in an array of 4, and sometimes I am seeing an `argmax` result of `4` or `5`. I captured some inputs below.

```rust
let ref x = ag::placeholder(&[-1, 4]);
let ref a = ag::argmax(&x, 1, false);

let ref x_val = array![[0.262881, 0.2613406, 0.26295722, 0.26295722]].into_dyn();
let ref feed = [(x, x_val)];
println!("{}", a.eval(feed));
```
Outputs
```
[5]
```

And in python
```python
>>> import numpy as np
>>> np.argmax([0.262881, 0.2613406, 0.26295722, 0.26295722])
2
```

**Comment by shanegibbs** [comment]
From what I can tell, the binary mask (in [reduction_ops.rs](https://github.com/raskr/rust-autograd/blob/b56c89d5445b1366e189d24623c06ee975deac6e/src/ops/reduction_ops.rs#L291-L301)) is returning multiple results when they are equal. It then does a dot product between the indices and in the binary mask, which can result in a value higher than the index.

I now notice that index `2` and `3` above have the same values. And those indices summed is where the `5` comes from.

**Comment by raskr** [comment]
#5 resolved this.
