### ISSUE TITLE
Alternatives for `tf.where()`

### ISSUE THREAD

**Issue by laocaoshilaocao** [raskr/rust-autograd#45]
Hi, i am working on a simple kmeans clustering algorithm using `autogard`
I want to achieve the same result as this TF code:
```
assignments = tf.constant([1, 0, 0])
c = 1
tf.where(tf.equal(assignments, c))
```
It simply returns the indices where the condition is True.
I wanna ask do you have any idea of simple alternative method in autogard?
Or i should again make my own custom defined op?

**Comment by raskr** [comment]
> simple kmeans clustering algorithm using autogard

Cool, would you add that in the example dir if you can afford?
> I wanna ask do you have any idea of simple alternative method in autogard?
Or i should again make my own custom defined op?

Yes, probably you have to impl a custom op...

**Comment by laocaoshilaocao** [comment]
> Cool, would you add that in the example dir if you can afford?

Yes i can do that after i finish. It is still a very "ugly" code :)

> Yes, probably you have to impl a custom op...

I am trying to do that using exiting graph methods, which is more practical i believe.

**Comment by laocaoshilaocao** [comment]
One related question is how could i update the `variable` using` autograd`?
The situation is like:
```
let centroids_value: Arc<RwLock<ag::NdArray<f64>>> = into_shared(rng.glorot_uniform(&[xxx]));
let points: Arc<RwLock<ag::NdArray<f64>>> = into_shared(array![xxx]);
for epoch in 0..2 {
    ag::with(|g| {
      (calculate the new centroid)
      g.eval(&[centroids_v] , &[]);
  });
}

```

**Comment by raskr** [comment]
if the epoch number is small, you can just swap the `with` and `for`. (but the large num of epochs would cause graph size  overflow)
The preferred way is defining the Op using [ndarray's assign](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.assign). It would be great if you send a PR about this!

**Comment by raskr** [comment]
[SGD](https://github.com/raskr/rust-autograd/blob/master/src/optimizers/sgd.rs)'s impl may be useful  for `Assign`.

**Comment by laocaoshilaocao** [comment]
>  swap the with and for
What do you mean by swap `with` and `for`? I don't find the` ag::for` is a correct expression.

> SGD's impl may be useful for Assign.
I am going to have a check of that.

**Comment by laocaoshilaocao** [comment]
Hi, i made the code as follow:

```
struct Assign;

impl ag::op::Op<f64> for Assign {
    fn compute(
        &self,
        ctx: &mut ag::op::ComputeContext<f64>,
    ) {
        ctx.input_mut(0).assign(&ctx.input(1));
        ctx.append_empty_output();
    }

    fn grad(&self, ctx: &mut ag::op::GradientContext<f64>) {
        ctx.append_input_grad(None);
    }
}

fn assign<'graph>(x: &Tensor<'graph>,  y: &Tensor<'graph>, g: &'graph ag::Graph<f64>)
-> Tensor<'graph> {
    ag::Tensor::builder()
           .set_inputs(&[Input::new_mut(x), Input::new(y)])
           .build(g, Assign)
}
```

However, when i tried to eval it use some very simple example like:

```
let centroids_value: Arc<RwLock<ag::NdArray<f64>>> = into_shared(rng.glorot_uniform(&[2, 2]));
let centroids_v = g.variable(centroids_value.clone()); 
let const_x = g.constant(array![[1.0,2.0], [1.0,2.0]]);

let update_ops = assign(&centroids_v, &const_x, g);
g.eval(&[update_ops] , &[]);
```
I always got the error `thread 'main' panicked at 'Bad op impl of network::Assign: cannot perform mutable borrowing for input(0)'`. Do u have any idea what is the wrong point of the code?

**Comment by laocaoshilaocao** [comment]
I also had a try of `SGD`, i wrote some test like this:

```
let centroids_v = g.variable(array![[1.0,2.0], [1.0,4.0]]);
let new_centroids_v = (&centroids_v + 1.0);
let sgd = ag::optimizers::sgd::SGD { lr: 0.1 };
let update_ops: &[ag::Tensor<f64>]  = &sgd.compute_updates(([new_centroids_v]).to_vec(), [const_x].to_vec(), g);
```
It gives the same error `'Bad op impl of autograd::ops::gradient_descent_ops::sgd::SGDOp<f64>: cannot perform mutable borrowing for input(0)'`
It doesn't show error if i directly use `[centroids_v].to_vec()` as the `sgd.compute_updates` input.

**Comment by laocaoshilaocao** [comment]
Hi, i am in development and usage of `assign` method.
However, i found i always met an error like this `thread 'main' panicked at 'Bad op impl of network::test::Assign: cannot perform mutable borrowing for input(0)'`. 
My `method` is like this:

```
struct Assign;

impl ag::op::Op<f64> for Assign {
    fn compute(
        &self,
        ctx: &mut ag::op::ComputeContext<f64>,
    ) {
        ctx.input_mut(0).assign(&ctx.input(1));
        ctx.append_empty_output();
    }

    fn grad(&self, ctx: &mut ag::op::GradientContext<f64>) {
        ctx.append_input_grad(None);
    }
}

pub fn assign<'graph>(x: &Tensor<'graph>,  y: &Tensor<'graph>, g: &'graph ag::Graph<f64>)
-> Tensor<'graph> {
    ag::Tensor::builder()
           .set_inputs(&[Input::new_mut(x), Input::new(y)])
           .build(g, Assign)
}
```

One using situation is like this one:
```
let point_t_for_intial =  g.variable(points.clone()); 
let point_t_for_intial_2 = g.slice(point_t_for_intial, &[x], &[y]);

let update_ops_t = assign(&point_t_for_intial, &point_t_for_intial_2, g);
```

Do u have any idea how to solve this error?

**Comment by laocaoshilaocao** [comment]
I also suffer from the `NaN` problem a lot.
I met situation like this:

`let mean = (means / assignments_num);`

where `assignments_num is:[[0.0]] shape=[1, 1], strides=[1, 1]`
`means is: [[0.0, 0.0]] shape=[1, 2]`

I always got result `mean are: [[NaN, NaN]]`

Do u have any idea about this situation?

**Comment by raskr** [comment]
Sorry for the late reply.

> cannot perform mutable borrowing for input(0)

Are you declaring `x` as variable using `ag::variable`?

> I also suffer from the NaN problem a lot.

That's because ndarray doesn't check zero-div. Is it difficult to avoid zero-div?

**Comment by laocaoshilaocao** [comment]
> Are you declaring x as variable using ag::variable?

yes i did

> That's because ndarray doesn't check zero-div. Is it difficult to avoid zero-div?

It is a little bit hard since that comes from the `exp` calculation and i am trying to use some `Nan to inf` function using `g.minimum`

**Comment by raskr** [comment]
> i am trying to use some Nan to inf function using g.minimum

Cool, it might be worth considering the handling of zero-div in binary-ops

> yes i did

Oh really? This example passed:
```rust
struct Assign;

impl ag::op::Op<f64> for Assign {
    fn compute(
        &self,
        ctx: &mut ag::op::ComputeContext<f64>,
    ) {
        ctx.input_mut(0).assign(&ctx.input(1));
        ctx.append_empty_output();
    }

    fn grad(&self, ctx: &mut ag::op::GradientContext<f64>) {
        ctx.append_input_grad(None);
    }
}

type Tensor<'a> = ag::Tensor<'a, f64>;

pub fn assign<'graph>(x: &Tensor<'graph>,  y: &Tensor<'graph>, g: &'graph ag::Graph<f64>)
                      -> Tensor<'graph> {
    ag::Tensor::builder()
        .set_inputs(&[ag::tensor::Input::new_mut(x), ag::tensor::Input::new(y)])
        .build(g, Assign)
}

use self::ag::NdArray;
use ag::{tensor::Constant, tensor::Variable, with};
use ndarray::array;

#[test]
fn test() {
    ag::with(|g| {
        let a = g.variable(ndarray::arr1(&[1., 2., 3.]));
        let b = g.zeros(&[3]);
        let c = assign(&a, &b, g);
        c.eval(&[]);
        
        println!("{:?}", a.get_variable_array());
    });
}
```
Result:
```rust
Some(RwLock { data: [0.0, 0.0, 0.0] shape=[3], strides=[1], layout=C | F (0x3), dynamic ndim=1 })
```

**Comment by raskr** [comment]
You can do `where` using the new `Tensor::map` method
