### ISSUE TITLE
Could I get a value "0" when it is not differentiable at any variable ,No panic?

### ISSUE THREAD

**Issue by Dirreke** [raskr/rust-autograd#56]
When I get the differential of constant at variable, I hope I can get the value "0" or an option of error, but it returns panic

**Comment by raskr** [comment]
[grad_helper](https://docs.rs/autograd/2.0.0-rc3/autograd/optimizers/fn.grad_helper.html) doesn't panic, but this may not be what you want.
Getting 0 is impossible currently.

**Comment by raskr** [comment]
Fixed in the master head
